dependencies:
  - conda-forge::numpy=1.19.1
  - conda-forge::scipy=1.5.2
  - conda-forge::matplotlib=3.3.0
  - conda-forge::scikit-learn=0.23.1
  - conda-forge::pyyaml=5.3.1
  - conda-forge::pydotplus=2.0.2
  - conda-forge::cython=0.29.21
  - conda-forge::pyspark=2.4.0
  - conda-forge::pyfpgrowth=1.0
  - conda-forge::rpy2=3.3.2
  - conda-forge::pip=20.2.2
  - pip:
    - auto-sklearn==0.8.0
    - git+https://github.com/Yu-Group/iterative-Random-Forest.git@bd85f69e3
    - git+https://github.com/shifwang/treeinterpreter.git@6ea6e91

